# Site
url: "https://www.gokturkdegerleme.com"
lang: tr
title: "Göktürk Değerleme"
sub_title: "Gayrimenkul Danışmanlığı"
description: "Göktürk ve çevresinde gayrimenkul sahiplerinin doğru kararlar almasına yardımcı olmak amacıyla bölgesel piyasa bilgisi ve gayrimenkul danışmanlığı."
copyright: '<a href="https://www.melihkocaturk.com">Melih Kocatürk</a>'
words_per_minute: 190

# Permalinks
permalink: /:title

# Pagination
paginate: 5
paginate_path: /sayfa:num/

# Google Analytics
google_analytics: G-5TLMYTWK28

# Contact
contact:
  address: "Göktürk, Eyüpsultan, İstanbul"
  gsm: +90 546 566 55 09
  email: melih.kocaturk@icloud.com

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
